import { prisma } from '../../database/prisma';
import { Money } from '../../utils/decimal';
import { ApiError } from '../../utils/response';
import { AuditService } from '../../middleware/audit.middleware';

export class AdminService {
  /**
   * High-level executive platform statistics
   */
  static async getPlatformStats() {
    const [
      totalUsers,
      totalTransactions,
      transactions,
      activeLoans,
      pendingKYC,
      openRiskAlerts,
      supportTickets,
    ] = await Promise.all([
      prisma.user.count(),
      prisma.transaction.count(),
      prisma.transaction.findMany({ select: { amount: true, currency: true } }),
      prisma.loan.count({ where: { status: 'ACTIVE' } }),
      prisma.kYCVerification.count({ where: { status: 'PENDING' } }),
      prisma.riskAlert.count({ where: { status: 'OPEN' } }),
      prisma.supportTicket.count({ where: { status: 'OPEN' } }),
    ]);

    const totalVolume = transactions.reduce((acc, t) => Money.add(acc, t.amount.toString()), Money.parse(0));

    return {
      totalUsers,
      totalTransactions,
      totalVolumeUSD: totalVolume.toNumber(),
      activeLoans,
      pendingKYC,
      openRiskAlerts,
      openSupportTickets: supportTickets,
    };
  }

  /**
   * Search and filter all registered customers
   */
  static async getUsers(query?: { search?: string; status?: string }) {
    const where: any = {};
    if (query?.status) where.status = query.status;
    if (query?.search) {
      where.OR = [
        { email: { contains: query.search } },
        { firstName: { contains: query.search } },
        { lastName: { contains: query.search } },
      ];
    }

    return prisma.user.findMany({
      where,
      include: {
        roles: { include: { role: true } },
        kycProfile: true,
        wallets: { include: { balances: true } },
      },
      orderBy: { createdAt: 'desc' },
      take: 100,
    });
  }

  /**
   * Change customer account status (e.g. LOCK, SUSPEND, ACTIVATE)
   */
  static async updateUserStatus(
    adminId: string,
    targetUserId: string,
    dto: { status: string; reason?: string },
    req?: any
  ) {
    const user = await prisma.user.findUnique({
      where: { id: targetUserId },
    });

    if (!user) {
      throw new ApiError('User not found', 404, 'NOT_FOUND');
    }

    const updated = await prisma.user.update({
      where: { id: targetUserId },
      data: { status: dto.status as any },
    });

    await AuditService.log({
      userId: adminId,
      action: 'ADMIN_USER_STATUS_CHANGE',
      entityType: 'User',
      entityId: targetUserId,
      details: { newStatus: dto.status, reason: dto.reason },
      req,
    });

    return updated;
  }

  /**
   * Get all compliance risk alerts generated by rule engines
   */
  static async getRiskAlerts() {
    return prisma.riskAlert.findMany({
      include: {
        transaction: {
          include: {
            wallet: {
              include: {
                user: { select: { email: true, firstName: true, lastName: true } },
              },
            },
          },
        },
      },
      orderBy: { createdAt: 'desc' },
    });
  }

  /**
   * Review and resolve or dismiss a risk alert
   */
  static async reviewRiskAlert(
    adminId: string,
    alertId: string,
    dto: { status: 'RESOLVED' | 'DISMISSED'; notes?: string },
    req?: any
  ) {
    const alert = await prisma.riskAlert.findUnique({
      where: { id: alertId },
    });

    if (!alert) {
      throw new ApiError('Risk alert not found', 404, 'NOT_FOUND');
    }

    const updated = await prisma.riskAlert.update({
      where: { id: alertId },
      data: {
        status: dto.status,
      },
    });

    await AuditService.log({
      userId: adminId,
      action: 'ADMIN_RISK_ALERT_REVIEWED',
      entityType: 'RiskAlert',
      entityId: alertId,
      details: dto,
      req,
    });

    return updated;
  }

  /**
   * Query global immutable audit logs
   */
  static async getAuditLogs() {
    return prisma.auditLog.findMany({
      include: {
        user: { select: { email: true, firstName: true, lastName: true } },
      },
      orderBy: { createdAt: 'desc' },
      take: 100,
    });
  }
}
